# Generated by Django 3.2.5 on 2022-03-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'J'), ('K', 'K'), ('Q', 'Q'), ('A', 'A')], max_length=100, unique=True, verbose_name='')),
                ('color', models.CharField(choices=[('sapdes', '♤'), ('diamonds', '♢'), ('hearts', '♡'), ('clubs', '♧')], max_length=100, unique=True, verbose_name='')),
            ],
        ),
    ]
