# Generated by Django 3.2.5 on 2022-03-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oko', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
