# Generated by Django 3.2.5 on 2022-03-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oko.card')),
            ],
        ),
    ]
