# Generated by Django 3.2.5 on 2022-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oko', '0003_alter_player_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
